// src/mockData/products.js
const mockProducts = [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      price: "$49.99",
      image: "https://example.com/images/product1.jpg",
      description: "High-quality sound with noise-cancellation and long-lasting battery.",
    },
    {
      id: 2,
      name: "In-Ear Noise-Cancelling Earphones",
      price: "$29.99",
      image: "https://example.com/images/product2.jpg",
      description: "Compact design with exceptional bass and comfort fit.",
    },
    {
      id: 3,
      name: "Over-Ear Studio Headphones",
      price: "$89.99",
      image: "https://example.com/images/product3.jpg",
      description: "Perfect for studio recording and mixing with high-definition audio.",
    },
    {
      id: 4,
      name: "Sport Wireless Earbuds",
      price: "$59.99",
      image: "https://example.com/images/product4.jpg",
      description: "Sweat-resistant, secure fit, ideal for workouts and outdoor activities.",
    },
    {
      id: 5,
      name: "Portable Headphone Amplifier",
      price: "$39.99",
      image: "https://example.com/images/product5.jpg",
      description: "Boosts audio output for high-impedance headphones.",
    },
    {
      id: 6,
      name: "Hi-Fi Bluetooth Over-Ear Headphones",
      price: "$129.99",
      image: "https://example.com/images/product6.jpg",
      description: "Luxury design with high-fidelity sound and powerful bass.",
    },
    {
      id: 7,
      name: "Gaming Headset with Surround Sound",
      price: "$69.99",
      image: "https://example.com/images/product7.jpg",
      description: "Immersive 7.1 surround sound for an unparalleled gaming experience.",
    },
    {
      id: 8,
      name: "Noise-Isolating Studio Headphones",
      price: "$109.99",
      image: "https://example.com/images/product8.jpg",
      description: "Professional-grade sound quality with noise isolation.",
    },
    {
      id: 9,
      name: "True Wireless Earbuds with Charging Case",
      price: "$34.99",
      image: "https://example.com/images/product9.jpg",
      description: "Compact and convenient with up to 15 hours of battery life.",
    },
    {
      id: 10,
      name: "ANC Over-Ear Headphones",
      price: "$139.99",
      image: "https://example.com/images/product10.jpg",
      description: "Active noise-canceling technology for immersive sound.",
    },
    {
      id: 11,
      name: "Bone Conduction Wireless Headphones",
      price: "$79.99",
      image: "https://example.com/images/product11.jpg",
      description: "Open-ear design allows for awareness of surroundings, perfect for outdoor use.",
    },
    {
      id: 12,
      name: "Audiophile Grade Headphones",
      price: "$299.99",
      image: "https://example.com/images/product12.jpg",
      description: "Top-notch sound quality, ideal for music enthusiasts.",
    },
    {
      id: 13,
      name: "Budget-Friendly Over-Ear Headphones",
      price: "$19.99",
      image: "https://example.com/images/product13.jpg",
      description: "Affordable yet powerful headphones for everyday use.",
    },
    {
      id: 14,
      name: "Foldable Wireless Headphones",
      price: "$59.99",
      image: "https://example.com/images/product14.jpg",
      description: "Convenient foldable design with Bluetooth connectivity.",
    },
    {
      id: 15,
      name: "Wireless Earbuds with Microphone",
      price: "$24.99",
      image: "https://example.com/images/product15.jpg",
      description: "Crystal clear sound with built-in microphone for calls.",
    },
    {
      id: 16,
      name: "Kids Safe Volume-Limiting Headphones",
      price: "$15.99",
      image: "https://example.com/images/product16.jpg",
      description: "Volume-limiting technology to protect young ears.",
    },
    {
      id: 17,
      name: "Waterproof Wireless Earphones",
      price: "$44.99",
      image: "https://example.com/images/product17.jpg",
      description: "IPX7 waterproof rating, ideal for swimming and outdoor activities.",
    },
    {
      id: 18,
      name: "Luxury Over-Ear Wooden Headphones",
      price: "$199.99",
      image: "https://example.com/images/product18.jpg",
      description: "Premium wooden finish with exceptional sound quality.",
    },
    {
      id: 19,
      name: "Lightweight Sport Headphones",
      price: "$39.99",
      image: "https://example.com/images/product19.jpg",
      description: "Ergonomic design with secure fit for active use.",
    },
    {
      id: 20,
      name: "True Wireless Earbuds with Noise Cancellation",
      price: "$99.99",
      image: "https://example.com/images/product20.jpg",
      description: "Compact, true wireless design with active noise cancellation.",
    },
  ];
  
  export default mockProducts;
  